### ISSUE TITLE
Does not work on live (Firebase, Netlify)

### ISSUE THREAD

**Issue by MetaBureau** [Eckhardt-D/nuxt-fire-auth#1]
Hi, I am having an issue where this works locally (dev, build and generate), but when deployed to firebase hosting, the session does not persist with page refresh.

Any ideas?

**Comment by Eckhardt-D** [comment]
Hi @MetaBureau sorry for the late reply. For this to work you will have to either host the entire app on a server that allows nodejs or change some of the logic to support static mode too because we're making use of nuxtServerInit and middleware which isn't available when hosted on Firebase / Netlify.

> Please check the updated repository - I created a branch `static-firebase` that handles the logic if the app is hosted statically. Go through the readme and ping me if you have any questions.

[Here is a link to the repo branch](https://github.com/Eckhardt-D/nuxt-fire-auth/tree/static-firebase)

I use Heroku or Now for hosting SSR version (free too). It has to run npm run start / yarn start. This spins up the server. When you run generate and serve the static files through netlify or firebase, there is no server for the middleware to work on. To have this work you'll have to use cloud functions or an api to handle users and change some of the logic in the app. 

The reason why generate and serve is working on reload locally and not online is quite confusing - I'm not sure what the difference is there. It may be the redirect settings or something BUT

The middleware and nuxtServerInit in the store are definitely not running on static versions. That means we never check the request for the cookie and re-set the user to the store. If you `console.log(this.$store.state.users.user)` on mounted or created you'll see it's null and we should be redirecting from the middleware.


Cheers!

**Comment by MetaBureau** [comment]
Hello and sorry too for the late reply :)
I have it working on Firebase ... the issue as I understand it is that the cookie must be named "__session" and not "access_token" otherwise it is removed by firebase.
